---
title: "Prediction Market Price, Polling Average, and Vote Percent"
author: "Brendan Chapuis"
date: "4/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}

library(readr)
library(tidyverse)

```

```{r data, include = FALSE}

dem_primary <- read_csv("data/processed-data/dem_primary.csv") %>% 
  select(-X1)

final_results_data <- read_csv("data/processed-data/final_results_data.csv") %>% 
  select(-X1)

```

```{r}



```


```{r market_and_votes, echo = FALSE}

final_results_data %>%
  mutate(winner = ifelse(winner == 1, "Yes", "No")) %>% 
  ggplot(aes(x = poll_estimate, y = vote_percent)) +
  geom_point(aes(color = winner), alpha = 0.75) +
  stat_smooth(method="lm", formula = y~x, se=TRUE) +
  theme_minimal() +
  theme(legend.position="bottom") +
  labs(title = "Relationship Between Final Polling Average and Percent of Vote",
       subtitle = "for Candidates in 2020 Democratic Primaries and Caucuses",
       x = "Final Polling Average from FiveThirtyEight",
       y = "Percent of Vote in Election",
       color = "Election Winner")

```

``` {r poll_and_votes, echo = FALSE}

final_results_data %>%
  mutate(winner = ifelse(winner == 1, "Yes", "No")) %>% 
  ggplot(aes(x = market_close, y = vote_percent)) +
  geom_point(aes(color = winner), alpha = 0.75) +
  stat_smooth(method="lm",
                formula=y ~ poly(x, 3, raw=TRUE)) +
  theme_minimal() +
  theme(legend.position="bottom") +
  labs(title = "Relationship Between Final Prediction Market Price and Vote Percent",
       subtitle = "for Candidates in 2020 Democratic Primaries and Caucuses",
       x = "Final Closing Market Price on PredictIt",
       y = "Percent of Vote in Election",
       color = "Election Winner")

```

