---
title: "Prediction Market Price, Polling Average, and Vote Percent"
author: "Brendan Chapuis"
date: "4/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}

library(readr)
library(tidyverse)

```

```{r data, include = FALSE}

dem_primary <- read_csv(
  "dem_primary.csv",
  col_types = cols(
    year = col_double(),
    state = col_character(),
    name = col_character(),
    date = col_date(format = ""),
    contest_date = col_date(format = ""),
    market_close = col_double(),
    poll_estimate = col_double(),
    poll_trend_adjusted = col_double(),
    date_dropped = col_date(format = ""),
    vote_percent = col_double(),
    winner = col_double()
  )
)

final_results <- dem_primary %>%
  filter(date == contest_date - 1)

```

```{r market_and_votes, echo = FALSE}

# Relationship between market price and vote percent

dem_primary %>%
  filter(date == contest_date - 1) %>%
  mutate(winner = ifelse(winner == 1, "Yes", "No")) %>%
  ggplot(aes(x = poll_estimate, y = vote_percent)) +
  geom_point(aes(color = winner), alpha = 0.75) +
  stat_smooth(method = "lm",
              formula = y ~ x,
              se = TRUE) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    title = "Relationship Between Final Polling Average and Percent of Vote",
    subtitle = "for Candidates in 2016/2020 Democratic Primaries and Caucuses",
    x = "Final Polling Average from FiveThirtyEight",
    y = "Percent of Vote in Election",
    color = "Election Winner"
  )

```

``` {r poll_and_votes, echo = FALSE}

# Relationship between polling average and vote percent

dem_primary %>%
  filter(date == contest_date - 1) %>%
  mutate(winner = ifelse(winner == 1, "Yes", "No")) %>%
  ggplot(aes(x = market_close, y = vote_percent)) +
  geom_point(aes(color = winner), alpha = 0.75) +
  stat_smooth(method = "lm",
              formula = y ~ poly(x, 3, raw = TRUE)) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(
    title = "Relationship Between Final Prediction Market Price and Vote Percent",
    subtitle = "for Candidates in 2016/2020 Democratic Primaries and Caucuses",
    x = "Final Closing Market Price on PredictIt",
    y = "Percent of Vote in Election",
    color = "Election Winner"
  )

```

```{r winner_regression, echo = FALSE}

# Using logistic regression to model probability of winning

final_results %>%
  ggplot(aes(x = market_close, y = winner)) +
  geom_point(alpha = 0.3) +
  theme_grey() +
  stat_smooth(
    method = "glm",
    method.args = list(family = "binomial"),
    se = FALSE
  ) +
  labs(
    title = "Probability of Winning an Election Based on Market Price",
    subtitle = "Using a Logistic Regression Model",
    x = "Market Price on PredictIt.org",
    y = "Probability of Winning"
  )

```

```{r over_time, echo = FALSE}

# Changes in accuracy over time

predictions_over_time %>%
  pivot_longer(
    cols = c(market, poll),
    names_to = "prediction_type",
    values_to = "value"
  ) %>%
  ggplot(aes(x = days_before, y = value, color = prediction_type)) +
  geom_line() +
  theme_grey() +
  scale_x_reverse() +
  labs(
    title = "Changes in Prediction Accuracy Over Time",
    subtitle = "Calculated As Percent of Elections Correctly Predicted",
    x = "Days Before Election",
    y = "Accuracy of Predictions",
    color = "Prediction Type"
  ) +
  scale_color_discrete(labels = c("Prediction Market Price", "Polling Average")) +
  theme(legend.position = "bottom")


```

